algorithm: bayes
spec:
  metric: val_loss
  objective: minimize
  maxCombo: 100
  seed: 42
  retryLimit: 20
parameters:
  n_hidden:
    type: integer
    min: 20
    max: 2000
    scalingType: uniform
  n_rnn_layers:
    type: integer
    min: 1
    max: 10
    scalingType: uniform
  p_dropout:
    type: float
    mu: 0.3
    sigma: 0.1
    scalingType: normal
